#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  8 19:07:20 2026

@author: jiawenzou
"""

import streamlit as st
import os

# --- Page Config ---
st.set_page_config(
    page_title="NYISO Price",
    page_icon="⚡",
    layout="wide"
)

# --- Hero Banner Image ---
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
IMAGE_PATH = os.path.join(CURRENT_DIR, "images", "BannerPic.png")

if os.path.exists(IMAGE_PATH):
    st.image(IMAGE_PATH, use_column_width=True)
else:
    st.warning("Banner image not found. Please check: images/BannerPic.png")

# --- Title Section ---
st.markdown("""
# ⚡ NYISO Real-Time Price Forecast
#### Electricity Market · Machine Learning · Real-Time Prediction
""")

st.markdown("---")

# --- Project Description ---
st.markdown("""
## Project Overview

This project develops an interactive Streamlit application for forecasting 
NYISO real-time electricity prices using market, temporal, weather, and location-based features.

The app allows users to input key predictors such as day-ahead market price, 
forecast load, weather conditions, time variables, and NYISO zone. 
Based on these inputs, users can compare predictions generated by multiple machine learning models.

The goal is to provide an accessible interface for understanding how different factors 
contribute to real-time electricity price variation across New York’s electricity market.
""")

st.markdown("---")

# --- Journey Section ---
st.markdown("## App Navigation")

st.markdown("""
This application includes several key sections:

1. **Make Predictions**  
   Enter feature values and generate real-time electricity price forecasts.

2. **Model Comparison**  
   Compare predictions across different machine learning models.

3. **Data Sources**  
   Review the dataset, variables, and feature definitions used in the project.

4. **Project Background**  
   Understand the motivation, market context, and modeling framework.
""")

st.info("Use the sidebar navigation to move between different sections of the app.")

st.markdown("---")

# --- Team Info ---
st.markdown("""
## Meet the Team

- **Akshay Kalyan** — [LinkedIn](https://www.linkedin.com/in/akshay-kalyan-907b91166/)
- **Terry Zhang** — [LinkedIn](https://www.linkedin.com/in/tianrui-terry-zhang/)
- **Jiawen Zou** — [LinkedIn](https://www.linkedin.com/in/jiawen-zou-66a511259/)
""")

st.markdown("---")

# --- Footer ---
st.caption("© 2026 · School of International and Public Affairs · Columbia University")